name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: uv venv

      - name: Install Dependencies
        run: uv pip install -e .[dev]

      - name: Lint with flake8
        run: uv run flake8 src

      - name: Test with pytest
        run: uv run pytest

      - name: Type check with mypy
        run: uv run mypy src

      - name: Security check with bandit
        run: uv run bandit -r src
